/*
 * Testdriver source generated by TESSY
 *
 * (c) Razorcat Development GmbH
 *
 * DO NOT EDIT THIS FILE !
 *
 *
 * File          : Slave Header (ts_add_s.h)
 * Testpath      : C:/Users/Sowjanya/Projects/TESSY/STUB_E~1/tessy\work\00000401\00000403\00000404\00000405
 * Modulename    : New Module
 * Testobjectname: add
 * Date          : 09.07.2020
 * Time          : 15:12:06
 * Tessy Version : 4.2.8
 *
 */

#if !defined (__TS_SLAVE_H)
   #define __TS_SLAVE_H


#endif /* !defined __TS_SLAVE_H */
