
/*
 * File generated by TESSY.
 * DO NOT EDIT THIS FILE!
 */

 /* Allow main as testobject */
#define main  ts_main
#define TESSY_SOURCE_01

/* stubfunction counters */
#include "ts_stubcounter.h"

int sum(int,int);
int c,a,b;
int add()
{
	c = sum(a,b);
	return c;
}


/****************************************************************/
/* T E S S Y  C O D E                                           */
/****************************************************************/

#define __TS_THIS_IS_THE_SLAVE__

/*
 * external variables
 */

#include "tstcomm.h"
#include "ts_add_s.h"
#include "ts_usr.h"
#include "ts_stub_declarations.h"


/*
 * Returnvalue
 */
int TS_TESTOBJECT_RETURN;

/*
 * Stub Variables
 */
extern char TESSY_use_value(void);

/*
 * Receive Testdata from master
 */
void TESSY_receive_TD01(void) {

   /* Globals */
   if (TESSY_use_value()) {a = tstcomm_get_long();}
   if (TESSY_use_value()) {b = tstcomm_get_long();}
   if (TESSY_use_value()) {c = tstcomm_get_long();}
}

void TESSY_send_TD01(void) {

   /* Globals */
   tstcomm_put_long(c);
}


/* Return */
void TESSY_send_return(void) {
   tstcomm_put_long(TS_TESTOBJECT_RETURN);
}

/*
 * DO NOT EDIT THIS FILE!
 *
 * This file is automatically generated each time a test
 * is executed and all changes made to this file will be lost.
 */
#include "ts_usr.h"
#include "ts_add_s.h"


#include "tsteval.h"

#ifndef TS_CURRENT_TESTCASE_DEFINED
	/* Current Testcase / Teststep and repeatcount*/
	extern TESSY_uint32   TS_CURRENT_TESTCASE;
	extern TESSY_uint32   TS_CURRENT_TESTSTEP;
	extern TESSY_uint32   TS_REPEAT_COUNT;
#endif


/*
 * User definitions
 */


/*
* User code to execute before test execution starts.
 */
void ts_tobj_prolog (void) {

}

/*
* User code to execute after test execution finished.
 */
void ts_tobj_epilog (void) {

}

/*
 * This function is called each time just before
 * a specific testcase and teststep is executed.
 */
void ts_tc_prolog (void) {
}


/*
 * This function is called each time just after
 * a specific testcase and teststep was executed.
 */
void ts_tc_epilog (void) {
}

void TESSY_TestobjectCall(void) {
   TS_TESTOBJECT_RETURN = add();
}

#include "tsteval.h"

/* Current Testcase / Teststep and repeatcount*/
extern TESSY_uint32 TS_CURRENT_TESTCASE;
extern TESSY_uint32 TS_CURRENT_TESTSTEP;
extern TESSY_uint8  TS_FAULT_INJECTION;
extern TESSY_uint32  TS_REPEAT_COUNT;


#include "ts_stubcounter.h"
